Resources:
  s3bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: demo-abhijith-bucket123
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
          SSEAlgorithm: AES256
      Tags:
        - Key: demo
          Value: yes