Description: Creates a Security group and an EC2 webserver on AWS
Parameters:
  InstanceName:
    Description: Enter the name of the instance
    Type: String
    Default: CF-instance
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter the instance type you want default in t2.micro
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the keypair you want to use for this instance
  SGDescription:
    Description: Enter a description for security group
    Type: String
  SGName:
    Description: Enter a name for SG
    Default: CF_SG
    Type: String

Resources:
  SG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: 
        Ref: SGDescription
      GroupName:
        Ref: SGName
      SecurityGroupIngress: 
     
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

      Tags: 
      - Key: cool
        Value: yes
      VpcId: vpc-c7b872ac

  Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-068257025f72f470d
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName
      Monitoring: False
      SecurityGroupIds: 
      - Ref: SG
      Tags: 
      - Key: cool
        Value: Yes
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            apy update -y
            apt install -y apache2
            systemctl start apache2
            systemctl enable apache2
            echo ?Hello World from $(hostname -f)? > /var/www/html/index.html

Outputs:
  serverIP:
    Description: public IP of server IP
    Value: 
      Fn::GetAtt: [Instance, PublicIp ]